from PyQt5 import QtCore, QtGui, QtWidgets
import Translate
import Language_Country_Abbreviations
from gtts import gTTS
from audioplayer import AudioPlayer

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1000, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_clear_text = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear_text.setFlat(True)
        self.pushButton_clear_text.setObjectName("pushButton_clear_text")
        self.verticalLayout_2.addWidget(self.pushButton_clear_text)
        self.pushButton_translate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_translate.setFlat(True)
        self.pushButton_translate.setObjectName("pushButton_translate")
        self.verticalLayout_2.addWidget(self.pushButton_translate)
        self.pushButton_speech = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_speech.setFlat(True)
        self.pushButton_speech.setObjectName("pushButton_speech")
        self.verticalLayout_2.addWidget(self.pushButton_speech)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_languages_origin = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_languages_origin.setObjectName("comboBox_languages_origin")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.comboBox_languages_origin.addItem("")
        self.verticalLayout.addWidget(self.comboBox_languages_origin)
        self.textEdit_text = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_text.setObjectName("textEdit_text")
        self.verticalLayout.addWidget(self.textEdit_text)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBox_languages_destination = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_languages_destination.setObjectName("comboBox_languages_destination")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.comboBox_languages_destination.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_languages_destination)
        self.textEdit_result = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_result.setReadOnly(True)
        self.textEdit_result.setObjectName("textEdit_result")
        self.verticalLayout_3.addWidget(self.textEdit_result)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 4, 1, 1)
        self.pushButton_speech_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_speech_2.setFlat(True)
        self.pushButton_speech_2.setObjectName("pushButton_speech_2")
        self.gridLayout.addWidget(self.pushButton_speech_2, 0, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_clear_text.clicked.connect(self.textEdit_text.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.commands()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_clear_text.setText(_translate("MainWindow", "Clear"))
        self.pushButton_translate.setText(_translate("MainWindow", "Translate"))
        self.pushButton_speech.setText(_translate("MainWindow", "Speech"))
        self.comboBox_languages_origin.setItemText(0, _translate("MainWindow", "Detect language"))
        self.comboBox_languages_origin.setItemText(1, _translate("MainWindow", "Afrikaans"))
        self.comboBox_languages_origin.setItemText(2, _translate("MainWindow", "Albanian"))
        self.comboBox_languages_origin.setItemText(3, _translate("MainWindow", "Amharic"))
        self.comboBox_languages_origin.setItemText(4, _translate("MainWindow", "Arabic"))
        self.comboBox_languages_origin.setItemText(5, _translate("MainWindow", "Armenian"))
        self.comboBox_languages_origin.setItemText(6, _translate("MainWindow", "Azerbaijani"))
        self.comboBox_languages_origin.setItemText(7, _translate("MainWindow", "Basque"))
        self.comboBox_languages_origin.setItemText(8, _translate("MainWindow", "Belarusian"))
        self.comboBox_languages_origin.setItemText(9, _translate("MainWindow", "Bengali"))
        self.comboBox_languages_origin.setItemText(10, _translate("MainWindow", "Bosnian"))
        self.comboBox_languages_origin.setItemText(11, _translate("MainWindow", "Bulgarian"))
        self.comboBox_languages_origin.setItemText(12, _translate("MainWindow", "Catalan"))
        self.comboBox_languages_origin.setItemText(13, _translate("MainWindow", "Cebuano"))
        self.comboBox_languages_origin.setItemText(14, _translate("MainWindow", "Chichewa"))
        self.comboBox_languages_origin.setItemText(15, _translate("MainWindow", "Chinese"))
        self.comboBox_languages_origin.setItemText(16, _translate("MainWindow", "Corsican"))
        self.comboBox_languages_origin.setItemText(17, _translate("MainWindow", "Croatian"))
        self.comboBox_languages_origin.setItemText(18, _translate("MainWindow", "Czech"))
        self.comboBox_languages_origin.setItemText(19, _translate("MainWindow", "Danish"))
        self.comboBox_languages_origin.setItemText(20, _translate("MainWindow", "Dutch"))
        self.comboBox_languages_origin.setItemText(21, _translate("MainWindow", "English"))
        self.comboBox_languages_origin.setItemText(22, _translate("MainWindow", "Esperanto"))
        self.comboBox_languages_origin.setItemText(23, _translate("MainWindow", "Estonian"))
        self.comboBox_languages_origin.setItemText(24, _translate("MainWindow", "Filipino"))
        self.comboBox_languages_origin.setItemText(25, _translate("MainWindow", "Finnish"))
        self.comboBox_languages_origin.setItemText(26, _translate("MainWindow", "French"))
        self.comboBox_languages_origin.setItemText(27, _translate("MainWindow", "Frisian"))
        self.comboBox_languages_origin.setItemText(28, _translate("MainWindow", "Galician"))
        self.comboBox_languages_origin.setItemText(29, _translate("MainWindow", "Georgian"))
        self.comboBox_languages_origin.setItemText(30, _translate("MainWindow", "German"))
        self.comboBox_languages_origin.setItemText(31, _translate("MainWindow", "Greek"))
        self.comboBox_languages_origin.setItemText(32, _translate("MainWindow", "Gujarati"))
        self.comboBox_languages_origin.setItemText(33, _translate("MainWindow", "Haitian Creole"))
        self.comboBox_languages_origin.setItemText(34, _translate("MainWindow", "Hausa"))
        self.comboBox_languages_origin.setItemText(35, _translate("MainWindow", "Hawaiian"))
        self.comboBox_languages_origin.setItemText(36, _translate("MainWindow", "Hebrew"))
        self.comboBox_languages_origin.setItemText(37, _translate("MainWindow", "Hindi"))
        self.comboBox_languages_origin.setItemText(38, _translate("MainWindow", "Hmong"))
        self.comboBox_languages_origin.setItemText(39, _translate("MainWindow", "Hungarian"))
        self.comboBox_languages_origin.setItemText(40, _translate("MainWindow", "Icelandic"))
        self.comboBox_languages_origin.setItemText(41, _translate("MainWindow", "Igbo"))
        self.comboBox_languages_origin.setItemText(42, _translate("MainWindow", "Indonesian"))
        self.comboBox_languages_origin.setItemText(43, _translate("MainWindow", "Irish"))
        self.comboBox_languages_origin.setItemText(44, _translate("MainWindow", "Italian"))
        self.comboBox_languages_origin.setItemText(45, _translate("MainWindow", "Japanese"))
        self.comboBox_languages_origin.setItemText(46, _translate("MainWindow", "Javanese"))
        self.comboBox_languages_origin.setItemText(47, _translate("MainWindow", "Kannada"))
        self.comboBox_languages_origin.setItemText(48, _translate("MainWindow", "Kazakh"))
        self.comboBox_languages_origin.setItemText(49, _translate("MainWindow", "Khmer"))
        self.comboBox_languages_origin.setItemText(50, _translate("MainWindow", "Kinyarwanda"))
        self.comboBox_languages_origin.setItemText(51, _translate("MainWindow", "Korean"))
        self.comboBox_languages_origin.setItemText(52, _translate("MainWindow", "Kurdish (Kurmanji)"))
        self.comboBox_languages_origin.setItemText(53, _translate("MainWindow", "Kyrgyz"))
        self.comboBox_languages_origin.setItemText(54, _translate("MainWindow", "Lao"))
        self.comboBox_languages_origin.setItemText(55, _translate("MainWindow", "Latin"))
        self.comboBox_languages_origin.setItemText(56, _translate("MainWindow", "Latvian"))
        self.comboBox_languages_origin.setItemText(57, _translate("MainWindow", "Lithuanian"))
        self.comboBox_languages_origin.setItemText(58, _translate("MainWindow", "Luxembourgish"))
        self.comboBox_languages_origin.setItemText(59, _translate("MainWindow", "Macedonian"))
        self.comboBox_languages_origin.setItemText(60, _translate("MainWindow", "Malagasy"))
        self.comboBox_languages_origin.setItemText(61, _translate("MainWindow", "Malay"))
        self.comboBox_languages_origin.setItemText(62, _translate("MainWindow", "Malayalam"))
        self.comboBox_languages_origin.setItemText(63, _translate("MainWindow", "Maltese"))
        self.comboBox_languages_origin.setItemText(64, _translate("MainWindow", "Maori"))
        self.comboBox_languages_origin.setItemText(65, _translate("MainWindow", "Marathi"))
        self.comboBox_languages_origin.setItemText(66, _translate("MainWindow", "Mongolian"))
        self.comboBox_languages_origin.setItemText(67, _translate("MainWindow", "Myanmar (Burmese)"))
        self.comboBox_languages_origin.setItemText(68, _translate("MainWindow", "Nepali"))
        self.comboBox_languages_origin.setItemText(69, _translate("MainWindow", "Norwegian"))
        self.comboBox_languages_origin.setItemText(70, _translate("MainWindow", "Odia (Oriya)"))
        self.comboBox_languages_origin.setItemText(71, _translate("MainWindow", "Pashto"))
        self.comboBox_languages_origin.setItemText(72, _translate("MainWindow", "Persian"))
        self.comboBox_languages_origin.setItemText(73, _translate("MainWindow", "Polish"))
        self.comboBox_languages_origin.setItemText(74, _translate("MainWindow", "Portuguese"))
        self.comboBox_languages_origin.setItemText(75, _translate("MainWindow", "Punjabi"))
        self.comboBox_languages_origin.setItemText(76, _translate("MainWindow", "Romanian"))
        self.comboBox_languages_origin.setItemText(77, _translate("MainWindow", "Russian"))
        self.comboBox_languages_origin.setItemText(78, _translate("MainWindow", "Samoan"))
        self.comboBox_languages_origin.setItemText(79, _translate("MainWindow", "Scots Gaelic"))
        self.comboBox_languages_origin.setItemText(80, _translate("MainWindow", "Serbian"))
        self.comboBox_languages_origin.setItemText(81, _translate("MainWindow", "Sesotho"))
        self.comboBox_languages_origin.setItemText(82, _translate("MainWindow", "Shona"))
        self.comboBox_languages_origin.setItemText(83, _translate("MainWindow", "Sindhi"))
        self.comboBox_languages_origin.setItemText(84, _translate("MainWindow", "Sinhala"))
        self.comboBox_languages_origin.setItemText(85, _translate("MainWindow", "Slovak"))
        self.comboBox_languages_origin.setItemText(86, _translate("MainWindow", "Slovenian"))
        self.comboBox_languages_origin.setItemText(87, _translate("MainWindow", "Somali"))
        self.comboBox_languages_origin.setItemText(88, _translate("MainWindow", "Spanish"))
        self.comboBox_languages_origin.setItemText(89, _translate("MainWindow", "Sundanese"))
        self.comboBox_languages_origin.setItemText(90, _translate("MainWindow", "Swahili"))
        self.comboBox_languages_origin.setItemText(91, _translate("MainWindow", "Swedish"))
        self.comboBox_languages_origin.setItemText(92, _translate("MainWindow", "Tajik"))
        self.comboBox_languages_origin.setItemText(93, _translate("MainWindow", "Tamil"))
        self.comboBox_languages_origin.setItemText(94, _translate("MainWindow", "Tatar"))
        self.comboBox_languages_origin.setItemText(95, _translate("MainWindow", "Telugu"))
        self.comboBox_languages_origin.setItemText(96, _translate("MainWindow", "Thai"))
        self.comboBox_languages_origin.setItemText(97, _translate("MainWindow", "Turkish"))
        self.comboBox_languages_origin.setItemText(98, _translate("MainWindow", "Turkmen"))
        self.comboBox_languages_origin.setItemText(99, _translate("MainWindow", "Ukrainian"))
        self.comboBox_languages_origin.setItemText(100, _translate("MainWindow", "Urdu"))
        self.comboBox_languages_origin.setItemText(101, _translate("MainWindow", "Uyghur"))
        self.comboBox_languages_origin.setItemText(102, _translate("MainWindow", "Uzbek"))
        self.comboBox_languages_origin.setItemText(103, _translate("MainWindow", "Vietnamese"))
        self.comboBox_languages_origin.setItemText(104, _translate("MainWindow", "Welsh"))
        self.comboBox_languages_origin.setItemText(105, _translate("MainWindow", "Xhosa"))
        self.comboBox_languages_origin.setItemText(106, _translate("MainWindow", "Yiddish"))
        self.comboBox_languages_origin.setItemText(107, _translate("MainWindow", "Yoruba"))
        self.comboBox_languages_origin.setItemText(108, _translate("MainWindow", "Zulu"))
        self.comboBox_languages_destination.setItemText(0, _translate("MainWindow", "Afrikaans"))
        self.comboBox_languages_destination.setItemText(1, _translate("MainWindow", "Albanian"))
        self.comboBox_languages_destination.setItemText(2, _translate("MainWindow", "Amharic"))
        self.comboBox_languages_destination.setItemText(3, _translate("MainWindow", "Arabic"))
        self.comboBox_languages_destination.setItemText(4, _translate("MainWindow", "Armenian"))
        self.comboBox_languages_destination.setItemText(5, _translate("MainWindow", "Azerbaijani"))
        self.comboBox_languages_destination.setItemText(6, _translate("MainWindow", "Basque"))
        self.comboBox_languages_destination.setItemText(7, _translate("MainWindow", "Belarusian"))
        self.comboBox_languages_destination.setItemText(8, _translate("MainWindow", "Bengali"))
        self.comboBox_languages_destination.setItemText(9, _translate("MainWindow", "Bosnian"))
        self.comboBox_languages_destination.setItemText(10, _translate("MainWindow", "Bulgarian"))
        self.comboBox_languages_destination.setItemText(11, _translate("MainWindow", "Catalan"))
        self.comboBox_languages_destination.setItemText(12, _translate("MainWindow", "Cebuano"))
        self.comboBox_languages_destination.setItemText(13, _translate("MainWindow", "Chichewa"))
        self.comboBox_languages_destination.setItemText(14, _translate("MainWindow", "Chinese"))
        self.comboBox_languages_destination.setItemText(15, _translate("MainWindow", "Corsican"))
        self.comboBox_languages_destination.setItemText(16, _translate("MainWindow", "Croatian"))
        self.comboBox_languages_destination.setItemText(17, _translate("MainWindow", "Czech"))
        self.comboBox_languages_destination.setItemText(18, _translate("MainWindow", "Danish"))
        self.comboBox_languages_destination.setItemText(19, _translate("MainWindow", "Dutch"))
        self.comboBox_languages_destination.setItemText(20, _translate("MainWindow", "English"))
        self.comboBox_languages_destination.setItemText(21, _translate("MainWindow", "Esperanto"))
        self.comboBox_languages_destination.setItemText(22, _translate("MainWindow", "Estonian"))
        self.comboBox_languages_destination.setItemText(23, _translate("MainWindow", "Filipino"))
        self.comboBox_languages_destination.setItemText(24, _translate("MainWindow", "Finnish"))
        self.comboBox_languages_destination.setItemText(25, _translate("MainWindow", "French"))
        self.comboBox_languages_destination.setItemText(26, _translate("MainWindow", "Frisian"))
        self.comboBox_languages_destination.setItemText(27, _translate("MainWindow", "Galician"))
        self.comboBox_languages_destination.setItemText(28, _translate("MainWindow", "Georgian"))
        self.comboBox_languages_destination.setItemText(29, _translate("MainWindow", "German"))
        self.comboBox_languages_destination.setItemText(30, _translate("MainWindow", "Greek"))
        self.comboBox_languages_destination.setItemText(31, _translate("MainWindow", "Gujarati"))
        self.comboBox_languages_destination.setItemText(32, _translate("MainWindow", "Haitian Creole"))
        self.comboBox_languages_destination.setItemText(33, _translate("MainWindow", "Hausa"))
        self.comboBox_languages_destination.setItemText(34, _translate("MainWindow", "Hawaiian"))
        self.comboBox_languages_destination.setItemText(35, _translate("MainWindow", "Hebrew"))
        self.comboBox_languages_destination.setItemText(36, _translate("MainWindow", "Hindi"))
        self.comboBox_languages_destination.setItemText(37, _translate("MainWindow", "Hmong"))
        self.comboBox_languages_destination.setItemText(38, _translate("MainWindow", "Hungarian"))
        self.comboBox_languages_destination.setItemText(39, _translate("MainWindow", "Icelandic"))
        self.comboBox_languages_destination.setItemText(40, _translate("MainWindow", "Igbo"))
        self.comboBox_languages_destination.setItemText(41, _translate("MainWindow", "Indonesian"))
        self.comboBox_languages_destination.setItemText(42, _translate("MainWindow", "Irish"))
        self.comboBox_languages_destination.setItemText(43, _translate("MainWindow", "Italian"))
        self.comboBox_languages_destination.setItemText(44, _translate("MainWindow", "Japanese"))
        self.comboBox_languages_destination.setItemText(45, _translate("MainWindow", "Javanese"))
        self.comboBox_languages_destination.setItemText(46, _translate("MainWindow", "Kannada"))
        self.comboBox_languages_destination.setItemText(47, _translate("MainWindow", "Kazakh"))
        self.comboBox_languages_destination.setItemText(48, _translate("MainWindow", "Khmer"))
        self.comboBox_languages_destination.setItemText(49, _translate("MainWindow", "Kinyarwanda"))
        self.comboBox_languages_destination.setItemText(50, _translate("MainWindow", "Korean"))
        self.comboBox_languages_destination.setItemText(51, _translate("MainWindow", "Kurdish (Kurmanji)"))
        self.comboBox_languages_destination.setItemText(52, _translate("MainWindow", "Kyrgyz"))
        self.comboBox_languages_destination.setItemText(53, _translate("MainWindow", "Lao"))
        self.comboBox_languages_destination.setItemText(54, _translate("MainWindow", "Latin"))
        self.comboBox_languages_destination.setItemText(55, _translate("MainWindow", "Latvian"))
        self.comboBox_languages_destination.setItemText(56, _translate("MainWindow", "Lithuanian"))
        self.comboBox_languages_destination.setItemText(57, _translate("MainWindow", "Luxembourgish"))
        self.comboBox_languages_destination.setItemText(58, _translate("MainWindow", "Macedonian"))
        self.comboBox_languages_destination.setItemText(59, _translate("MainWindow", "Malagasy"))
        self.comboBox_languages_destination.setItemText(60, _translate("MainWindow", "Malay"))
        self.comboBox_languages_destination.setItemText(61, _translate("MainWindow", "Malayalam"))
        self.comboBox_languages_destination.setItemText(62, _translate("MainWindow", "Maltese"))
        self.comboBox_languages_destination.setItemText(63, _translate("MainWindow", "Maori"))
        self.comboBox_languages_destination.setItemText(64, _translate("MainWindow", "Marathi"))
        self.comboBox_languages_destination.setItemText(65, _translate("MainWindow", "Mongolian"))
        self.comboBox_languages_destination.setItemText(66, _translate("MainWindow", "Myanmar (Burmese)"))
        self.comboBox_languages_destination.setItemText(67, _translate("MainWindow", "Nepali"))
        self.comboBox_languages_destination.setItemText(68, _translate("MainWindow", "Norwegian"))
        self.comboBox_languages_destination.setItemText(69, _translate("MainWindow", "Odia (Oriya)"))
        self.comboBox_languages_destination.setItemText(70, _translate("MainWindow", "Pashto"))
        self.comboBox_languages_destination.setItemText(71, _translate("MainWindow", "Persian"))
        self.comboBox_languages_destination.setItemText(72, _translate("MainWindow", "Polish"))
        self.comboBox_languages_destination.setItemText(73, _translate("MainWindow", "Portuguese"))
        self.comboBox_languages_destination.setItemText(74, _translate("MainWindow", "Punjabi"))
        self.comboBox_languages_destination.setItemText(75, _translate("MainWindow", "Romanian"))
        self.comboBox_languages_destination.setItemText(76, _translate("MainWindow", "Russian"))
        self.comboBox_languages_destination.setItemText(77, _translate("MainWindow", "Samoan"))
        self.comboBox_languages_destination.setItemText(78, _translate("MainWindow", "Scots Gaelic"))
        self.comboBox_languages_destination.setItemText(79, _translate("MainWindow", "Serbian"))
        self.comboBox_languages_destination.setItemText(80, _translate("MainWindow", "Sesotho"))
        self.comboBox_languages_destination.setItemText(81, _translate("MainWindow", "Shona"))
        self.comboBox_languages_destination.setItemText(82, _translate("MainWindow", "Sindhi"))
        self.comboBox_languages_destination.setItemText(83, _translate("MainWindow", "Sinhala"))
        self.comboBox_languages_destination.setItemText(84, _translate("MainWindow", "Slovak"))
        self.comboBox_languages_destination.setItemText(85, _translate("MainWindow", "Slovenian"))
        self.comboBox_languages_destination.setItemText(86, _translate("MainWindow", "Somali"))
        self.comboBox_languages_destination.setItemText(87, _translate("MainWindow", "Spanish"))
        self.comboBox_languages_destination.setItemText(88, _translate("MainWindow", "Sundanese"))
        self.comboBox_languages_destination.setItemText(89, _translate("MainWindow", "Swahili"))
        self.comboBox_languages_destination.setItemText(90, _translate("MainWindow", "Swedish"))
        self.comboBox_languages_destination.setItemText(91, _translate("MainWindow", "Tajik"))
        self.comboBox_languages_destination.setItemText(92, _translate("MainWindow", "Tamil"))
        self.comboBox_languages_destination.setItemText(93, _translate("MainWindow", "Tatar"))
        self.comboBox_languages_destination.setItemText(94, _translate("MainWindow", "Telugu"))
        self.comboBox_languages_destination.setItemText(95, _translate("MainWindow", "Thai"))
        self.comboBox_languages_destination.setItemText(96, _translate("MainWindow", "Turkish"))
        self.comboBox_languages_destination.setItemText(97, _translate("MainWindow", "Turkmen"))
        self.comboBox_languages_destination.setItemText(98, _translate("MainWindow", "Ukrainian"))
        self.comboBox_languages_destination.setItemText(99, _translate("MainWindow", "Urdu"))
        self.comboBox_languages_destination.setItemText(100, _translate("MainWindow", "Uyghur"))
        self.comboBox_languages_destination.setItemText(101, _translate("MainWindow", "Uzbek"))
        self.comboBox_languages_destination.setItemText(102, _translate("MainWindow", "Vietnamese"))
        self.comboBox_languages_destination.setItemText(103, _translate("MainWindow", "Welsh"))
        self.comboBox_languages_destination.setItemText(104, _translate("MainWindow", "Xhosa"))
        self.comboBox_languages_destination.setItemText(105, _translate("MainWindow", "Yiddish"))
        self.comboBox_languages_destination.setItemText(106, _translate("MainWindow", "Yoruba"))
        self.comboBox_languages_destination.setItemText(107, _translate("MainWindow", "Zulu"))
        self.pushButton_speech_2.setText(_translate("MainWindow", "Speech"))

    def commands(self):  # command
        self.comboBox_languages_origin.setCurrentText("Detect language")
        self.comboBox_languages_destination.setCurrentText("English")
        self.events()

    def events(self):  # command
        self.comboBox_languages_origin.currentTextChanged.connect(self.change_language)
        self.comboBox_languages_destination.currentTextChanged.connect(self.change_language)

        self.pushButton_clear_text.clicked.connect(self.clear_text)
        self.pushButton_translate.clicked.connect(self.translate)
        self.pushButton_speech.clicked.connect(self.speech_text)
        self.pushButton_speech_2.clicked.connect(self.speech_result)

    def clear_text(self):
        self.textEdit_text.clear()
        self.textEdit_result.clear()

    def change_language(self):  # command
        if self.textEdit_text.toPlainText() == "":
            self.textEdit_result.clear()
        else:
            if self.comboBox_languages_origin.currentText() == "Detect language":
                self.textEdit_result.setText(Translate.translate(self.textEdit_text.toPlainText(), self.comboBox_languages_destination.currentText()))
            else:
                self.textEdit_result.setText(Translate.translate(self.textEdit_text.toPlainText(), self.comboBox_languages_destination.currentText(), self.comboBox_languages_origin.currentText()))

    def translate(self):  # command
        if self.textEdit_text.toPlainText() == "":
            self.textEdit_result.clear()
        else:
            if self.comboBox_languages_origin.currentText() == "Detect language":
                self.textEdit_result.setText(Translate.translate(self.textEdit_text.toPlainText(), self.comboBox_languages_destination.currentText()))
            else:
                self.textEdit_result.setText(Translate.translate(self.textEdit_text.toPlainText(), self.comboBox_languages_destination.currentText(), self.comboBox_languages_origin.currentText()))

    def speech_text(self):
        if self.comboBox_languages_origin.currentText() == "Detect language":
            Text_to_speech = gTTS(self.textEdit_text.toPlainText())
            Text_to_speech.save("Google_TTS.mp3")
            AudioPlayer("Google_TTS.mp3").play(block=True)
        else:
            Text_to_speech = gTTS(self.textEdit_text.toPlainText(), lang=self.comboBox_languages_origin.currentText())
            Text_to_speech.save("Google_TTS.mp3")
            AudioPlayer("Google_TTS.mp3").play(block=True)

    def speech_result(self):
        Text_to_speech = gTTS(self.textEdit_result.toPlainText(), lang=Language_Country_Abbreviations.language_to_code.get(self.comboBox_languages_destination.currentText()))
        Text_to_speech.save("Google_TTS.mp3")
        AudioPlayer("Google_TTS.mp3").play(block=True)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
